### ISSUE TITLE
Add per-API log level and reinstate GQL query logging

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/data-node#29]
There is currently one Gateway log level. Per-API log levels would be more useful.

In vegaprotocol/vega#2376, some GraphQL logging was removed because it was causing high CPU usage.

```toml
[Gateway]
  Level = "Info"
  [Gateway.Node]
    # no Level here
  [Gateway.GraphQL]
    # or here
  [Gateway.REST]
    # or here
```

## Tasks
* Add per-API log levels
* Reinstate logging that was removed in vegaprotocol/vega#2376, but make sure it's behind `if log.Level >= Debug {...}` so it causes near-zero CPU usage unless the GraphQL-specific log level is Debug.
* bonus points: split `loggingMiddleware` into `loggingMiddleware` and `metricsMiddleware`. Then only add `loggingMiddleware` to `options` if `log.Level >= Debug` https://github.com/vegaprotocol/vega/blob/44496cb879e07a0b9445bc123cd1149b69f7dd83/gateway/graphql/server.go#L127-L137
